name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-shared:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - "1.85"
    name: Test w. shared library (${{matrix.toolchain}} toolchain)
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.toolchain}}
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: |
          sudo add-apt-repository -u -y ppa:s-ramacher/picnic
          sudo apt install libpicnic-dev pkg-config
      - name: Test with default features
        run: cargo test
      - name: Test with all features
        run: cargo test --all-features
      - name: Test without std feature
        run: cargo test --no-default-features --features system --features picnic --features picnic3

  test-static:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain:
          - stable
          - "1.85"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: Test w. static-fallback (${{matrix.toolchain}} toolchain, ${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.toolchain}}
      - uses: Swatinem/rust-cache@v2
      - name: Test with default features
        run: cargo test
      - name: Test with all features
        run: cargo test --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo add-apt-repository -u -y ppa:s-ramacher/picnic
          sudo apt install libpicnic-dev pkg-config
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo add-apt-repository -u -y ppa:s-ramacher/picnic
          sudo apt install libpicnic-dev pkg-config
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all --all-features -- -D warnings
